basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: This is the API documentation for the GoRecipes application.
  title: GoRecipes API
  version: "1.0"
paths: {}
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
